- name: "Update Nginx conf"
  lineinfile:
    dest: /etc/nginx/nginx.conf
    regexp: '^\s*server 192.168.?[0-9]?[0-9]?[0-9].?[0-9]?[0-9]?[0-9];'
    firstmatch: yes
    line: "server {{ servername }}"

- name: restart nginx
  service: name=nginx state=restarted